### ISSUE TITLE
Linux - Undefined reference

### ISSUE THREAD

**Issue by secit** [imaginevision/libssp#1]
I can't compile with the Linux library since commit 51026544b1863a5985152825cb701714d4394848.
There was no problem with commit 051f1a32e9578b62f37a59cf867f0e6de081f99c.

This is the error I get when trying to 'make' the example (libssp_test.cpp):
```libssp_test.cpp:(.text+0x1c1): undefined reference to `imf::SspClient::SspClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, imf::Loop*, unsigned long, unsigned short, unsigned int)'```

**Comment by ailike** [comment]
fixed in 70754b69ae4c3a3712524a7dc044106ac77c94c5
